[phases.setup]
nixPkgs = ['php82', 'nodejs', 'npm']
cmds = [
    'php -v',
    'composer -V'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan storage:link || true',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan optimize'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}' 