[phases.setup]
nixPkgs = ['php82', 'nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan storage:link',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan optimize'
]

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/' 