[phases.setup]
nixPkgs = ['php82', 'nodejs', 'npm']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'vendor/bin/heroku-php-apache2 public/' 