[build]
builder = "NIXPACKS"
watchPatterns = ["composer.json", "package.json"]

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[build.steps]]
name = "Install composer dependencies"
command = "composer install --optimize-autoloader"

[[build.steps]]
name = "Install npm dependencies"
command = "npm install"

[[build.steps]]
name = "Build assets"
command = "npm run build"

[[deploy.lifecycle]]
name = "Cache and storage setup"
command = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link" 